LOGGING = False

STATISTICS_START_TIME = 0

N_RUNS = 1
N_SHOPS = 6

# SHOP_SAFETY_STOCK = 0  # inital value
SHOP_SAFETY_STOCK = 10 * 10  # optimal value

MODEL_PARAMS = {
    "INITIAL_WHOLESALE": 1920,
    "INITIAL_SHOP": 70,
    # "WHOLESALE_RESTOCK_AMOUNT": 800,  # initial value
    "WHOLESALE_RESTOCK_AMOUNT": 842,  # optimal value
    "WHOLESALE_SCHEDULED_AMOUNT": 1800,
    "SHOP_MAX_STOCK": SHOP_SAFETY_STOCK + 7 * 10,
    "SHOP_REORDER_POINT": SHOP_SAFETY_STOCK + 6 * 10,
}
